---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - "App Store"
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Music
  - News
  - Keynote
  - Numbers
  - Pages
  - MacPass
  - "Workspace ONE Intelligent Hub"
  - Catalog
  - TV
  - Freeform

dockitems_persist:
  - name: "Ghostty"
    path: "/Applications/Ghostty.app/"
    pos: 2
  - name: "Arc"
    path: "/Applications/Arc.app/"
    pos: 3
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 4
  - name: "Vault-UI"
    path: "/Applications/Vault-UI.app/"
    pos: 5
  - name: "Insomnia"
    path: "/Applications/Insomnia.app/"
    pos: 7
  - name: "Apache Netbeans"
    path: "/Applications/Apache NetBeans.app/"
    pos: 8
  - name: "Microsoft Teams"
    path: "/Applications/Microsoft Teams.app/"
    pos: 10

configure_sudoers: false
sudoers_custom_config: ""
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/adammcdonagh/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/git/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc
  - .gitconfig
  - .gitconfig-personal
  - .gitconfig-work
  - .config/ohmyposh/zen.toml
  - .config/pip/pip.conf
  - .m2/settings.xml
  - .aws/config
  - Library/Application Support/com.mitchellh.ghostty/config
  - Library/Application Support/com.mitchellh.ghostty/ghostty-shaders/crt-shader-with-chromatic-aberration-glow-scanlines-dot-matrix.glsl

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  # - autoconf
  - bash-completion
  - git
  - gpg
  - pinentry-mac
  - sqlite
  - node
  - php
  - openssl
  - jq
  - curl
  - wget
  - freetds
  - pyenv
  - direnv
  - tomcat@8
  # Tomcat 7 package has gone, so this will need manually installing
  - tomcat
  - zsh-syntax-highlighting
  - python3
  - coreutils
  - duti
homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - font-meslo-lg-nerd-font
  - font-meslo-for-powerline
  - font-hasklig
  - ghostty
  - insomnia
  - docker
  - arc
  - visual-studio-code
  - oracle-jdk
  - netbeans
  - gimp
  - sensiblesidebuttons
  - sqlitestudio
  - wireshark
  - parallels
  - alt-tab
  - raycast
  - stats
# Missing vault-ui (no cask exists)

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
  # - name: requests
  #   state: present
  # - name: black
  #   state: present
  # - name: flake8
  #   state: present
  # - name: flake8-bugbear
  #   state: present
  # - name: flake8-polyfill
  #   state: present
  # - name: flake8-use-fstring
  #   state: present
  # - name: pep8-naming
  #   state: present
  # - name: boto3
  #   state: present
  # - name: ansible
  #   state: present
  # - name: ansible-lint
  #   state: present
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
